name: Javascript client package

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted # ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - id: package-tag
        name: Determine tag for package
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION="nightly"
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            VERSION="develop"
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/release/* ]]; then
            VERSION="release"
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::$(echo $VERSION)"
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: "./go.mod"
          cache: false # no use on self-hosted runner
      - run: go version
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: package.json
          registry-url: "https://npm.pkg.github.com"
          scope: "@momentum-xyz"
      - id: npm-deps
        name: Install dependencies
        run: npm ci
      - id: publish
        name: Publish NPM package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --tag "${{ steps.package-tag.outputs.version }}"
