name: Python client package

on:
  workflow_dispatch:
  push:
    #    branches:
    #  - develop
    tags:
      - py@[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    runs-on: self-hosted # ubuntu-latest
    #strategy:
    #  matrix:
    #    os: [ubuntu-20.04, windows-2019, macOS-11]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
        with:
          fetch-depth: 0
      - id: go-fixup
        # Workaround for setup-go on self-hosted runner, without a $HOME
        name: Go fixup
        run: |
          echo "GOMODCACHE=/opt/go-cache/mod" >> $GITHUB_ENV
          echo "GOCACHE=/opt/go-cache/build" >> $GITHUB_ENV
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: "./go.mod"
          cache: false # no use on self-hosted runner

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
        with:
          python-version: '3.11'
      - name: Upgrade pip(x)
        run: |
          python -m pip install --upgrade pip pipx
      - name: Version
        working-directory: py
        run: |
          pipx run hatch version >> $GITHUB_STEP_SUMMARY
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.1
      - name: Build wheels
        run: python -m cibuildwheel --platform linux --archs x86_64 --output-dir build/wheelhouse py
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce  # v3.1.2
        with:
          name: wheels
          path: ./build/wheelhouse/*.whl
  pypi-publish:
    name: upload release to PyPI
    needs: [build_wheels]
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags')
    runs-on: self-hosted
    environment:
      name: pypi
      url: https://pypi.org/project/odyssey-posbus-client/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a  # v3.0.2
        with:
          name: wheels
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8  # v1.8.8

